/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CETECOM
 */
public class Jframe_pedido extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_pedido
     */
    public Jframe_pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tamañoTaco = new javax.swing.JLabel();
        jComboBox_tamañoTaco = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_mechada = new javax.swing.JRadioButton();
        jRadioButton_pollo = new javax.swing.JRadioButton();
        jRadioButton_cerdo = new javax.swing.JRadioButton();
        jRadioButton_vegetariano = new javax.swing.JRadioButton();
        jCheckBox_lechuga = new javax.swing.JCheckBox();
        jCheckBox_poroto = new javax.swing.JCheckBox();
        jCheckBox_tomate = new javax.swing.JCheckBox();
        jCheckBox_queso = new javax.swing.JCheckBox();
        jCheckBox_choclo = new javax.swing.JCheckBox();
        jCheckBox_cebolla = new javax.swing.JCheckBox();
        jCheckBox_guacamole = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField_nombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jButton_aceptar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jButton_agregarOtro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana1");

        jLabel_tamañoTaco.setText("Tamaño");

        jComboBox_tamañoTaco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Taco Chico", "Taco Mediano", "Taco Grande", "Big Taco" }));

        jLabel1.setText("Base");

        jLabel2.setText("Ingredientes");

        jRadioButton_mechada.setText("Mechada");

        jRadioButton_pollo.setText("Pollo");

        jRadioButton_cerdo.setText("Cerdo");

        jRadioButton_vegetariano.setText("Vegetariano");

        jCheckBox_lechuga.setText("Lechuga");

        jCheckBox_poroto.setText("Poroto");
        jCheckBox_poroto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_porotoActionPerformed(evt);
            }
        });

        jCheckBox_tomate.setText("Tomate");
        jCheckBox_tomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_tomateActionPerformed(evt);
            }
        });

        jCheckBox_queso.setText("Queso Rallado");

        jCheckBox_choclo.setText("Choclo");

        jCheckBox_cebolla.setText("Cebolla");

        jCheckBox_guacamole.setText("Guacamole");

        jLabel3.setText("Nombre del Cliente");

        jLabel4.setText("Total");

        jButton_aceptar.setText("Aceptar");
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        jButton_limpiar.setText("Limpiar");

        jButton_cancelar.setText("Cancelar");

        jButton_agregarOtro.setText("Agregar otro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton_vegetariano)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jRadioButton_mechada)
                                    .addComponent(jRadioButton_pollo)
                                    .addComponent(jRadioButton_cerdo))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox_lechuga)
                                        .addGap(35, 35, 35)
                                        .addComponent(jCheckBox_choclo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_tomate)
                                            .addComponent(jCheckBox_poroto))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_guacamole)
                                            .addComponent(jCheckBox_cebolla)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jCheckBox_queso))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_tamañoTaco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_tamañoTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_agregarOtro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_cancelar)
                                .addGap(49, 49, 49)
                                .addComponent(jButton_limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_aceptar)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tamañoTaco)
                    .addComponent(jComboBox_tamañoTaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_agregarOtro))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_mechada)
                    .addComponent(jCheckBox_lechuga)
                    .addComponent(jCheckBox_choclo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_pollo)
                    .addComponent(jCheckBox_tomate)
                    .addComponent(jCheckBox_cebolla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_cerdo)
                    .addComponent(jCheckBox_poroto)
                    .addComponent(jCheckBox_guacamole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_vegetariano)
                    .addComponent(jCheckBox_queso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aceptar)
                    .addComponent(jButton_limpiar)
                    .addComponent(jButton_cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_tomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_tomateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_tomateActionPerformed

    private void jCheckBox_porotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_porotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_porotoActionPerformed

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_agregarOtro;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JCheckBox jCheckBox_cebolla;
    private javax.swing.JCheckBox jCheckBox_choclo;
    private javax.swing.JCheckBox jCheckBox_guacamole;
    private javax.swing.JCheckBox jCheckBox_lechuga;
    private javax.swing.JCheckBox jCheckBox_poroto;
    private javax.swing.JCheckBox jCheckBox_queso;
    private javax.swing.JCheckBox jCheckBox_tomate;
    private javax.swing.JComboBox<String> jComboBox_tamañoTaco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_tamañoTaco;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JRadioButton jRadioButton_cerdo;
    private javax.swing.JRadioButton jRadioButton_mechada;
    private javax.swing.JRadioButton jRadioButton_pollo;
    private javax.swing.JRadioButton jRadioButton_vegetariano;
    private javax.swing.JTextField jTextField_nombreCliente;
    // End of variables declaration//GEN-END:variables
}
